export const PY_RULES = [
  {
    id: 'python.dangerous_sinks',
    title: 'Dangerous code-execution sink',
    severity: 'CRITICAL',
    category: 'code-exec',
    confidence: 0.85,
    re: /(?<![.\w])(eval|exec|compile)\s*\(|\bos\.(system|popen|exec[lv]?[pe]*)\s*\(|\bsubprocess\.(run|call|check_output|check_call|Popen)\s*\(|(?<![.\w])__import__\s*\(|(?<![.\w])getattr\s*\(\s*__builtins__/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'model load / forward()',
    message: 'Model code invokes an arbitrary code-execution primitive. Under trust_remote_code this runs in the host process the moment the model is imported.',
    remediation: 'Remove the eval/exec/os.system/subprocess call. Load this model only after reviewing the pinned revision; never with trust_remote_code=True from an untrusted publisher.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.pickle_deserialization',
    title: 'Unsafe deserialization',
    severity: 'CRITICAL',
    category: 'deserialization',
    confidence: 0.9,

    re: /\b(pickle|cpickle|dill|_pickle|cloudpickle)\.(loads?|Unpickler)\s*\(|\bjsonpickle\.(decode|loads)\s*\(|\bmarshal\.loads?\s*\(|\btorch\.(load|jit\.load)\s*\(|\byaml\.(unsafe_load|load\s*\((?![^)]*Loader\s*=\s*yaml\.(Safe|Full)Loader))|\bjoblib\.load\s*\(|\bskops\.io\.load\s*\(|\bshelve\.open\s*\(|\bnumpy\.load\s*\([^)]*allow_pickle\s*=\s*True|\b(pandas|pd)\.read_pickle\s*\(|\bmlflow\.[\w.]+\.load_model\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'weight / config file',
    message: 'Deserializes data with a pickle-backed loader. A crafted file runs arbitrary code via __reduce__ on load - the primary model-hub malware vector.',
    remediation: 'Load weights from safetensors (use_safetensors=True). For YAML use yaml.safe_load; for numpy set allow_pickle=False; avoid torch.load / cloudpickle / pandas.read_pickle / mlflow.load_model on untrusted files.',
    cwe: 'CWE-502',
  },
  {
    id: 'python.trust_remote_code',
    title: 'Model loaded with trust_remote_code',
    severity: 'CRITICAL',
    category: 'remote-code',
    confidence: 0.95,

    codeOnly: true,
    re: /trust_remote_code\s*=\s*True/,
    sink: () => 'trust_remote_code=True',
    source: 'model repository',
    message: 'Loads a model/tokenizer/embedder with trust_remote_code=True, which imports and runs code shipped in the model repo inside the host process before any weights load - an instant RCE if the publisher, or a later silent revision, is malicious.',
    remediation: 'Remove trust_remote_code=True. Prefer a model with native transformers support, or pin revision= to a specific reviewed commit hash and read the custom modeling code first.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.dataset_remote_code',
    title: 'Dataset loaded with trust_remote_code',
    severity: 'CRITICAL',
    category: 'remote-code',
    confidence: 0.9,
    codeOnly: true,

    re: /\bload_dataset\s*\((?=[^)]*trust_remote_code\s*=\s*True)/,
    sink: () => 'load_dataset(trust_remote_code=True)',
    source: 'dataset repository',
    message: 'Loads a Hugging Face dataset with trust_remote_code=True, which imports and runs the dataset\'s Python loading script in the host process - arbitrary code execution from the dataset publisher.',
    remediation: 'Remove trust_remote_code=True. Use a non-script dataset format (Parquet/Arrow/CSV/JSON), or pin revision= to a reviewed commit and read the loading script first.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.native_code_load',
    title: 'Loads a native library (ctypes)',
    severity: 'HIGH',
    category: 'code-exec',
    confidence: 0.85,
    re: /\bctypes\.(CDLL|WinDLL|OleDLL|PyDLL|cdll|windll|oledll)\b|\bcdll\.LoadLibrary\s*\(|\bwindll\.LoadLibrary\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'native library',
    message: 'Loads a native/shared library via ctypes. Model code has no reason to dlopen libc or an arbitrary .so/.dll - it is an execution primitive (e.g. ctypes.CDLL("libc.so.6").system(cmd)).',
    remediation: 'Remove the ctypes native-library load from model/loader code. Treat any model that dlopens libraries on load as hostile.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.dynamic_file_exec',
    title: 'Loads and executes a Python file at runtime',
    severity: 'HIGH',
    category: 'code-exec',
    confidence: 0.85,
    re: /\bSourceFileLoader\s*\(|\bspec_from_file_location\s*\(|\bimp\.load_source\s*\(|\bexec_module\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'file path',
    message: 'Imports and executes a Python file from a path at runtime (SourceFileLoader / spec_from_file_location / imp.load_source). This runs code that is not statically visible as an import - a common way to hide an execution path.',
    remediation: 'Remove runtime file-based module loading from model code. Import only reviewed, statically-visible modules.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.torch_remote_code',
    title: 'Loads/executes remote or native code via torch',
    severity: 'CRITICAL',
    category: 'remote-code',
    confidence: 0.9,
    re: /\btorch\.hub\.load\s*\(|\btorch\.hub\.load_state_dict_from_url\s*\(|\btorch\.package\.PackageImporter\s*\(|\btorch\.classes\.load_library\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'remote repo / packaged code',
    message: 'Fetches and executes code that is not in this repository (torch.hub.load runs a remote hubconf.py; load_state_dict_from_url pulls a pickle; PackageImporter / load_library run packaged or native code) - an instant RCE at load time.',
    remediation: 'Do not torch.hub.load untrusted repos (and never with trust_repo=True on an unreviewed source). Load a local, reviewed safetensors checkpoint instead.',
    cwe: 'CWE-494',
  },
  {
    id: 'python.weights_only_false',
    title: 'torch.load with weights_only=False',
    severity: 'CRITICAL',
    category: 'deserialization',
    confidence: 0.95,
    re: /\btorch\.load\s*\([^)]*weights_only\s*=\s*False/,
    sink: () => 'torch.load(..., weights_only=False)',
    source: 'weight file',
    message: 'torch.load is called with weights_only=False, which turns the safe (default since torch 2.6) tensor-only loader back into the full pickle unpickler - a crafted checkpoint then runs arbitrary code via __reduce__ on load.',
    remediation: 'Remove weights_only=False (let it default to True), or load from safetensors. Only ever disable it for a checkpoint you built yourself.',
    cwe: 'CWE-502',
  },
  {
    id: 'python.keras_unsafe_load',
    title: 'Keras load with safe_mode disabled',
    severity: 'HIGH',
    category: 'deserialization',
    confidence: 0.85,
    re: /\bsafe_mode\s*=\s*False/,
    sink: () => 'safe_mode=False',
    source: 'model file',
    message: 'A Keras/TensorFlow model is loaded with safe_mode=False, which allows deserialization of Lambda layers - arbitrary Python bytecode that executes the moment the model loads (CVE-2024-3660 / CVE-2025-1550 class).',
    remediation: 'Remove safe_mode=False. Load only models you trust; a Lambda layer in an untrusted model is remote code execution regardless of format (.h5 ignores safe_mode entirely).',
    cwe: 'CWE-502',
  },
  {
    id: 'python.langchain_code_exec',
    title: 'LLM-driven code-execution component',
    severity: 'HIGH',
    category: 'agentic',
    confidence: 0.85,

    re: /\b(PythonREPL|PythonREPLTool|PythonAstREPLTool|PALChain|CPALChain|LLMMathChain|create_pandas_dataframe_agent|create_spark_dataframe_agent|create_csv_agent|PandasQueryEngine|PandasInstructionParser|CodeInterpreterToolSpec|CodeAgent|LocalPythonExecutor|local_python_executor|PythonInterpreterTool)\b|\bload_tools\s*\([^)]*['"](python_repl|terminal|shell|bash)/,
    sink: (m) => m[0].trim(),
    source: 'LLM output',
    message: 'Uses an agent-framework component that executes LLM-generated code (exec/eval on model output). If the model can be steered (prompt injection), this is remote code execution in the agent host (CVE-2023-29374 / CVE-2024-4181 class).',
    remediation: 'Avoid code-executing chains/tools on untrusted input. If unavoidable, run them in a locked-down sandbox with no host/network access and a strict output validator.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.autogen_local_exec',
    title: 'Agent executes LLM-written code locally',
    severity: 'HIGH',
    category: 'agentic',
    confidence: 0.75,

    re: /code_execution_config\s*=\s*\{|use_docker\s*=\s*False/,
    sink: (m) => m[0].replace(/\s*=\s*\{$/, '').trim(),
    source: 'LLM output',
    message: 'An AutoGen-style agent is configured to execute LLM-written code on the host (a dict code_execution_config / use_docker=False). Any prompt-injected instruction the model follows becomes code execution in the agent process.',
    remediation: 'Set code_execution_config=False, or require use_docker=True (an isolated container) with no host mounts and a locked-down image. Never run model-authored code directly on the host.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.langchain_serialized_load',
    title: 'Loads a serialized chain / prompt / agent',
    severity: 'HIGH',
    category: 'deserialization',
    confidence: 0.75,

    re: /\b(load_chain|load_prompt|load_agent)\s*\(|\bhub\.pull\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'serialized chain / hub',
    message: 'Deserializes a LangChain chain/prompt/agent from a file or the hub. The serialized config can name arbitrary classes to construct - a poisoned artifact is code execution when the object is built.',
    remediation: 'Build chains in code from reviewed source, not from an untrusted serialized artifact; if you must load one, pin and review it and never load from a user-supplied path/URL.',
    cwe: 'CWE-502',
  },
  {
    id: 'python.rag_unsafe_deser',
    title: 'Unsafe vector-store / RAG deserialization',
    severity: 'CRITICAL',
    category: 'deserialization',
    confidence: 0.9,
    re: /allow_dangerous_deserialization\s*=\s*True|\bFAISS\.load_local\s*\(|\b(pickle|joblib)\.load\s*\([^)]*(index|faiss|embedding|vector|chroma)/i,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'vector store / embedding index',
    message: 'Loads a RAG vector store or embedding index through a pickle-backed path (allow_dangerous_deserialization / FAISS.load_local / a pickled index). A poisoned index file executes arbitrary code the moment it is loaded - the embedding-store supply-chain vector.',
    remediation: 'Never set allow_dangerous_deserialization=True on an index you did not build. Rebuild the vector store from source documents in your own environment, or use a non-pickle store format.',
    cwe: 'CWE-502',
  },
  {
    id: 'python.mcp_client',
    title: 'MCP client integration (untrusted tool-output ingress)',

    severity: 'LOW',
    category: 'agentic',
    confidence: 0.55,

    re: /\bfrom\s+mcp\.client[\w.]*\s+import\b|\bimport\s+mcp\.client\b|\bmcp\.client\.\w+|\bfrom\s+mcp\s+import\b[^\n]*\bClientSession\b/,
    codeOnly: true,
    sink: (m) => m[0].trim(),
    source: 'MCP server tool output',
    message: 'Acts as an MCP client/host: opens a ClientSession to MCP servers and passes their tool descriptions and results back to a model. Every server it reaches is an untrusted-input ingress - a poisoned tool description or result can hijack the agent (prompt injection / tool poisoning).',
    remediation: 'Pin exactly which MCP servers this client may connect to and run each through governance before trusting it. Treat all server output as untrusted data, never instructions, and screen it (runtime firewall) before it reaches the model.',
    cwe: 'CWE-829',
  },
  {
    id: 'python.reduce_payload',
    title: 'Custom __reduce__ (pickle RCE gadget)',
    severity: 'CRITICAL',
    category: 'deserialization',
    confidence: 0.8,
    re: /def\s+__reduce__\s*\(|def\s+__reduce_ex__\s*\(|def\s+__setstate__\s*\(/,
    sink: (m) => m[0].replace(/^def\s+/, '').replace(/\s*\($/, '').trim(),
    message: 'Defines a pickle reduction hook. These execute on unpickling and are the classic gadget used to hide code-exec inside a serialized model object.',
    remediation: 'Verify why the class needs custom pickling. Do not unpickle objects from this repo; prefer safetensors serialization which has no code path.',
    cwe: 'CWE-502',
  },
  {
    id: 'python.network_egress',
    title: 'Network egress',

    severity: 'MEDIUM',
    category: 'egress',
    confidence: 0.5,
    re: /\b(requests|httpx)\.(get|post|put|request)\s*\(|\burllib\.request\.(urlopen|urlretrieve)\s*\(|\bsocket\.(socket|create_connection)\s*\(|\baiohttp\.ClientSession\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    source: 'network',
    message: 'Opens an outbound network connection. Normal in application code; in model/tokenizer code that should never phone out, or chained with a remote-code load, this is the exfiltration / second-stage-download shape.',
    remediation: 'Confirm the destination and payload. Model inference code should never make outbound requests; treat a phoning-out model as hostile until proven otherwise.',
    cwe: 'CWE-913',
  },
  {
    id: 'python.dynamic_import',
    title: 'Dynamic / obfuscated import',
    severity: 'HIGH',
    category: 'obfuscation',
    confidence: 0.7,
    re: /\bimportlib\.import_module\s*\(|\b__import__\s*\(\s*['"]?\s*(os|subprocess|socket|base64|marshal|ctypes)|\bexec\s*\(\s*(base64|bytes|marshal|codecs)/,
    sink: (m) => m[0].trim(),
    message: 'Imports or executes a module chosen at runtime, often to hide os/subprocess/socket usage from a quick read.',
    remediation: 'Resolve what is imported and why. Obfuscated dynamic imports in model code are a strong malware tell.',
    cwe: 'CWE-94',
  },
  {
    id: 'python.encoded_payload',
    title: 'Encoded blob decode',

    severity: 'LOW',
    category: 'obfuscation',
    confidence: 0.5,
    re: /\b(base64|codecs|binascii)\.(b64decode|decode|unhexlify)\s*\(|bytes\.fromhex\s*\(/,
    sink: (m) => m[0].replace(/\s*\($/, '').trim(),
    message: 'Decodes an encoded blob. Benign on its own (common in tokenizers/quantization), but the "decode then run it" packer combines this with eval/exec - see any decode-and-run chain finding on this file.',
    remediation: 'If this decode feeds eval/exec/import, decode the blob offline and inspect it. A lone decode of vocab/kernel data is expected.',
    cwe: 'CWE-506',
  },
  {
    id: 'python.gradio_public_share',
    title: 'Model UI exposed via public share tunnel',
    severity: 'MEDIUM',
    category: 'exposure',
    confidence: 0.8,
    re: /\.launch\s*\([^)]*share\s*=\s*True|\.queue\s*\([^)]*\)\.launch\s*\([^)]*share\s*=\s*True/,
    sink: () => 'launch(share=True)',
    message: 'Launches a Gradio/model UI with share=True, publishing a public tunnel URL to a locally-running model - anyone with the link can drive inference (and any tools wired to it) with no auth.',
    remediation: 'Remove share=True for anything beyond a throwaway demo. Bind to localhost or put the app behind authenticated ingress; never expose a tool-enabled agent this way.',
    cwe: 'CWE-668',
  },
  {
    id: 'python.hardcoded_ai_key',
    title: 'Hardcoded AI-provider API key',
    severity: 'MEDIUM',
    category: 'secret',
    confidence: 0.85,

    re: /['"](sk-ant-[A-Za-z0-9_-]{20,}|sk-[A-Za-z0-9]{20,}|hf_[A-Za-z0-9]{20,}|AIza[A-Za-z0-9_-]{20,}|gsk_[A-Za-z0-9]{20,})['"]/,
    sink: (m) => m[1].slice(0, 12) + '…',
    source: 'source literal',
    message: 'An AI-provider API key is hardcoded as a string literal. Anyone with read access to this repo can drain the account; committed keys are scraped within minutes.',
    remediation: 'Remove the literal and load the key from an environment variable / secret manager at runtime. Rotate the exposed key immediately.',
    cwe: 'CWE-798',
  },
  {
    id: 'python.env_exfil',
    title: 'Reads environment / secrets',
    severity: 'MEDIUM',
    category: 'secret',
    confidence: 0.5,
    re: /\bos\.environ\b|\bos\.getenv\s*\(|\bParameterStore|\bboto3\.client\s*\(\s*['"]s(ts|ecretsmanager)/,
    sink: (m) => m[0].trim(),
    source: 'process environment',
    message: 'Reads environment variables or a secrets store. Paired with network egress this is credential exfiltration.',
    remediation: 'Confirm the code has a legitimate need for the variable; model inference code generally should not read the environment.',
    cwe: 'CWE-200',
  },
];

export const PY_TAINT = {
  lang: 'python',
  ruleId: 'python.llm_output_to_sink',
  aiCall: /\.(a?generate|a?predict|a?invoke|a?run|complete|acomplete|chat|stream|__call__|predict_messages)\s*\(|\.(chat\.)?completions\.create\s*\(|\.messages\.create\s*\(|\bllm\s*\(/,
  execSink: /(?<![.\w])(eval|exec|compile)\s*\(|\bos\.(system|popen)\s*\(|\bsubprocess\.(run|call|check_output|check_call|Popen)\s*\(/g,
};
