export const CONFIG_RULES = [
  {
    id: 'json.automodel_usage',

    title: 'AutoModel bound to repo-shipped code (trust_remote_code)',
    severity: 'MEDIUM',
    category: 'remote-code',
    confidence: 0.8,
    re: /"(AutoModel[A-Za-z]*|AutoConfig)"\s*:\s*"([^"]+)"/,
    sink: (m) => `auto_map.${m[1]}`,
    message: 'config.json maps an Auto* class to code shipped in this repo. Loading with trust_remote_code imports and runs that code before any weights - review the publisher and the referenced module. (A dangerous sink in that module is reported separately at higher severity.)',
    remediation: 'Review the referenced module before loading, pin revision= to a reviewed commit, or use a model with native transformers support.',
    cwe: 'CWE-829',
  },
  {
    id: 'json.autotokenizer_usage',
    title: 'AutoTokenizer bound to remote code',
    severity: 'HIGH',
    category: 'remote-code',
    confidence: 0.8,
    re: /"(AutoTokenizer|AutoProcessor|AutoFeatureExtractor|AutoImageProcessor)"\s*:\s*"([^"]+)"/,
    sink: (m) => `auto_map.${m[1]}`,
    message: 'config maps a tokenizer/processor class to repo-shipped code, executed under trust_remote_code when the tokenizer loads.',
    remediation: 'Review the referenced tokenizer code before loading; prefer a model whose tokenizer ships with transformers.',
    cwe: 'CWE-829',
  },
  {
    id: 'json.trust_remote_code',
    title: 'Config declares trust_remote_code',
    severity: 'HIGH',
    category: 'remote-code',
    confidence: 0.85,
    re: /"trust_remote_code"\s*:\s*true/i,
    sink: () => '"trust_remote_code": true',
    message: 'The config pins trust_remote_code on, so any loader that honours it (transformers, sentence-transformers) will import and run the repo\'s custom code without the caller opting in.',
    remediation: 'Remove the trust_remote_code flag from the config and require callers to opt in explicitly against a reviewed, pinned revision.',
    cwe: 'CWE-94',
  },
  {
    id: 'json.custom_pipeline',
    title: 'Config binds a custom pipeline to remote code',
    severity: 'HIGH',
    category: 'remote-code',
    confidence: 0.8,
    re: /"custom_pipelines?"\s*:\s*[{"]/,
    sink: (m) => m[0].replace(/\s*:\s*[{"]$/, '').trim(),
    message: 'config.json declares a custom_pipeline, which binds the pipeline loader to code shipped in this repo - executed under trust_remote_code, before any weights, exactly like auto_map.',
    remediation: 'Remove the custom_pipeline entry, or pin revision= to a reviewed commit and read the referenced pipeline code before loading.',
    cwe: 'CWE-829',
  },
];
